name: Trigger Database Migrations

on:
  pull_request:
    types: [closed]

jobs:
  migrate-cdb:
    runs-on: ubuntu-latest
    if: github.event.pull_request.merged == true  # Only trigger on merged PRs

    steps:

      - name: Checkout branch repo
        uses: actions/checkout@v4
        with:
          path: branch
          fetch-depth: 0

      - name: Checkout main repo
        uses: actions/checkout@v4
        with:
          path: main
          ref: main

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"
          cache: "pip"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip uv
          uv pip install --system -r requirements.txt
        shell: bash

      - name: Compare branch to main
        working-directory: ${{ github.workspace }}/branch
        run: |
          CHANGED_FILES=()
          for schema_file in python/lsst/sdm_schemas/schemas/cdb_*.yaml; do
            diff_results=$(felis diff $schema_file ../main/python/lsst/sdm_schemas/schemas/$(basename $schema_file))
            if [ $? -ne 0 ]; then
                echo "Error running felis diff on $schema_file"
                exit 1
            fi
            if [ -n "$diff_results" ]; then
              echo "Schema file $schema_file has changed"
              echo "$diff_results"
              CHANGED_FILES+=($schema_file)
            fi
          done
          if [ ${#CHANGED_FILES[@]} -eq 0 ]; then
            echo "No schema files changed"
            exit 0
          else
            echo "Changed schema files: ${CHANGED_FILES[@]}"
          fi

      #- name: Check for changed cdb schemas
      #  run: |
      #    CHANGED_FILES=$(git diff --name-only origin/main..HEAD -- python/lsst/sdm_schemas/schemas)
      #    echo "Changed files: $CHANGED_FILES"
      #    if [ -z "$CHANGED_FILES" ]; then
      #      echo "No schema files changed"
      #      exit 0
      #    fi
      #    CHANGED_FILES=$(echo $CHANGED_FILES | grep -E '/cdb_.*\.yaml$')
      #    echo "Changed cdb schema files: $CHANGED_FILES"
      #    if [ -z "$CHANGED_FILES" ]; then
      #      echo "No cdb schema files changed"
      #      exit 0
      #    fi
      #    echo "Changed cdb schema files: $CHANGED_FILES"

      - name: Trigger migration workflow in consdb repository
        uses: peter-evans/repository-dispatch@v3
        with:
          token: ${{ secrets.REPO_DISPATCH_TOKEN }}
          repository: JeremyMcCormick/consdb-dm-47507
          event-type: migration
          client-payload: '{"branch_name": "${{ github.head_ref }}", "commit_sha": "${{ github.event.pull_request.merge_commit_sha }}"}'
